name: test
channels:
  - bioconda
  - conda-forge
dependencies:
  - gdown
  - snakemake-minimal 
  - fastqc
  - multiqc
  - bbmap
  - star
  - bioconductor-deseq2
  - subread
  - snakemake-wrapper-utils
